query Settings {
  setting {
    site_name
    site_title
    show_title
    breadcrumb
    darkmode
    autoimage
    authentication
    scrolltop
    articles_limit
    articles_loop_mode
    read_more
    logo_img {
      url
      caption
      alternativeText
    }
    email
    github
    twitter
    footer
    darkmode_settings {
      ...on ComponentThemesDarkMode {
        primary_fg {
          color
          density
          css
          tw_color
        }
        main_bg {
          color
          density
          css
          tw_color
        }
        header_fg {
          color
          density
          css
          tw_color
        }
        header_bg {
          color
          density 
          image {
            url
          }
          css
          tw_color
        }
        footer_fg {
          color
          density 
          css
          tw_color
        }
        footer_bg {
          color
          density 
          image {
            url
          }
          css
          tw_color
        }
        link_fg {
          color
          density 
          css
          tw_color
        }
        menu_fg {
          color
          density 
          css
          tw_color
        }
      }
    }
  }
}